services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - '12000:3000'
    volumes:
      - ./nextjs:/app
      - node_modules:/app/node_modules
    depends_on:
      - php
      - mailpit
    networks:
      - mynetwork
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    volumes:
      - ./php:/var/www/html
    networks:
      - mynetwork
  mailpit:
    image: axllent/mailpit
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - mynetwork
volumes:
  node_modules:

networks:
  mynetwork:
    driver: bridge
